### PR TITLE
Merge 'ThreeMammals:develop' to 'develop'

### PR DESCRIPTION
**Pull request by raman-m**
Let's update your repo with latest top-commits from parent repository.
That will allow to perform **rebase**-operation for feature branches without merge-commits.

### CODE REVIEW

**Comment by raman-m** [comment]
Mark,
Could you auto-approve and merge it without squash plz?

Merge option with fast-forwarding should be performed.
Thank you!

**Comment by raman-m** [comment]
Mark,
How was your weekend? 😄 

Please, merge the PR!

**Comment by raman-m** [comment]
@marklonquist  Hello!
Please sync **develop** branch of your fork!

**Comment by marklonquist** [comment]
i'm so sorry! I missed this entirely 😅

**Comment by raman-m** [comment]
It is better to press **Sync Fork** button! It allow to remove extra commits (fake [merge commits ahead](https://github.com/marklonquist/Ocelot/compare/ThreeMammals%3AOcelot%3Adevelop...develop)) too.
I use PR just to point your attention to the fact that repo is/was outdated.

**Comment by marklonquist** [comment]
yes I know - but for some reason that button was AWOL when I looked. I synced now though.

**Comment by raman-m** [comment]
There is [the diff](https://github.com/ThreeMammals/Ocelot/compare/develop...marklonquist:Ocelot:develop)!
Both develop branches should be identical! That's the goal of syncing.

**Pull request merged**
